import {
  sqliteTable,
  text,
  integer,
  real,
  index,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";

// ---------------------------------------------------------------------------
// PHASE 1 — voice_profile (singleton: always id = 1)
// ---------------------------------------------------------------------------
export const voiceProfile = sqliteTable("voice_profile", {
  id: integer("id").primaryKey({ autoIncrement: false }).default(1),
  rawText: text("raw_text").notNull(),
  parsedAt: integer("parsed_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(strftime('%s', 'now'))`),
  docxChecksum: text("docx_checksum").notNull(),
});

// ---------------------------------------------------------------------------
// PHASE 1–2 — topic_areas (seed table, 7 fixed rows)
// ---------------------------------------------------------------------------
export const topicAreas = sqliteTable("topic_areas", {
  id: integer("id").primaryKey({ autoIncrement: false }),
  name: text("name").notNull(),
  description: text("description").notNull(),
  keywords: text("keywords").notNull(), // JSON array stored as text
});

// ---------------------------------------------------------------------------
// PHASE 2 — posts (drafts + published posts)
// ---------------------------------------------------------------------------
export const posts = sqliteTable(
  "posts",
  {
    id: text("id").primaryKey(), // uuid — generated by application
    roughIdea: text("rough_idea"),
    sourceUrl: text("source_url"),       // article URL when drafted from /discover (D-08)
    sourceTitle: text("source_title"),   // article title when drafted from /discover (D-08)
    draftText: text("draft_text"),
    finalText: text("final_text"),
    // 5-dimension tagging (Phase 2)
    hookType: text("hook_type", {
      enum: ["question", "stat", "story", "hot_take", "confession", "contrast"],
    }),
    narrativeStructure: text("narrative_structure", {
      enum: ["hook_insight", "story_arc", "essay", "list"],
    }),
    topicId: integer("topic_id").references(() => topicAreas.id),
    scheduledTime: integer("scheduled_time", { mode: "timestamp" }),
    publishedAt: integer("published_at", { mode: "timestamp" }),
    linkedinPostUrl: text("linkedin_post_url"),
    // Engagement metrics (Phase 4 — manually entered or auto-pulled Phase 5)
    reactions: integer("reactions"),
    comments: integer("comments"),
    reposts: integer("reposts"),
    impressions: integer("impressions"),
    engagementRate: real("engagement_rate"), // (reactions + comments + reposts) / impressions
    metricsPulledAt: integer("metrics_pulled_at", { mode: "timestamp" }),
    status: text("status", {
      enum: ["draft", "published"],
    })
      .notNull()
      .default("draft"),
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .default(sql`(strftime('%s', 'now'))`),
  },
  (table) => ({
    topicIdx: index("posts_topic_idx").on(table.topicId),
    statusIdx: index("posts_status_idx").on(table.status),
    createdAtIdx: index("posts_created_at_idx").on(table.createdAt),
  })
);

// ---------------------------------------------------------------------------
// PHASE 3 — trending_items (RSS feed items + bookmarks)
// ---------------------------------------------------------------------------
export const trendingItems = sqliteTable(
  "trending_items",
  {
    id: text("id").primaryKey(), // uuid
    sourceType: text("source_type", {
      enum: ["rss", "bookmark"],
    }).notNull(),
    sourceUrl: text("source_url").notNull(),
    title: text("title"),
    summary: text("summary"),
    topicId: integer("topic_id").references(() => topicAreas.id),
    contentHash: text("content_hash").notNull(), // sha256 of url+title for dedup
    fetchedAt: integer("fetched_at", { mode: "timestamp" })
      .notNull()
      .default(sql`(strftime('%s', 'now'))`),
    expiresAt: integer("expires_at", { mode: "timestamp" }), // TTL for RSS items
  },
  (table) => ({
    topicIdx: index("trending_topic_idx").on(table.topicId),
    hashIdx: uniqueIndex("trending_hash_idx").on(table.contentHash),
  })
);

// ---------------------------------------------------------------------------
// PHASE 4–5 — performance_bias (singleton, updated weekly by Feedback Engine)
// ---------------------------------------------------------------------------
export const performanceBias = sqliteTable("performance_bias", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  computedAt: integer("computed_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(strftime('%s', 'now'))`),
  biasJson: text("bias_json").notNull(), // JSON: ranked tag combos per topic
});

// ---------------------------------------------------------------------------
// PHASE 4–5 — weekly_digests
// ---------------------------------------------------------------------------
export const weeklyDigests = sqliteTable("weekly_digests", {
  id: text("id").primaryKey(), // uuid
  weekEnding: text("week_ending").notNull(), // ISO date string: "2026-05-05"
  digestJson: text("digest_json").notNull(), // JSON: top performers, underperformers, recommendations
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(strftime('%s', 'now'))`),
});

// ---------------------------------------------------------------------------
// TypeScript inferred types — used by query functions throughout the app
// ---------------------------------------------------------------------------
export type VoiceProfile = typeof voiceProfile.$inferSelect;
export type NewVoiceProfile = typeof voiceProfile.$inferInsert;

export type TopicArea = typeof topicAreas.$inferSelect;
export type NewTopicArea = typeof topicAreas.$inferInsert;

export type Post = typeof posts.$inferSelect;
export type NewPost = typeof posts.$inferInsert;

export type TrendingItem = typeof trendingItems.$inferSelect;
export type NewTrendingItem = typeof trendingItems.$inferInsert;

export type PerformanceBias = typeof performanceBias.$inferSelect;
export type WeeklyDigest = typeof weeklyDigests.$inferSelect;
