import {
  pgTable,
  text,
  integer,
  real,
  index,
  uniqueIndex,
  timestamp,
  serial,
} from "drizzle-orm/pg-core";

// ---------------------------------------------------------------------------
// PHASE 1 — voice_profile (singleton: always id = 1)
// ---------------------------------------------------------------------------
export const voiceProfile = pgTable("voice_profile", {
  id: integer("id").primaryKey().default(1),
  rawText: text("raw_text").notNull(),
  parsedAt: timestamp("parsed_at").notNull().defaultNow(),
  docxChecksum: text("docx_checksum").notNull(),
});

// ---------------------------------------------------------------------------
// PHASE 1–2 — topic_areas (seed table, 7 fixed rows)
// ---------------------------------------------------------------------------
export const topicAreas = pgTable("topic_areas", {
  id: integer("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description").notNull(),
  keywords: text("keywords").notNull(), // JSON array stored as text
});

// ---------------------------------------------------------------------------
// PHASE 2 — posts (drafts + published posts)
// ---------------------------------------------------------------------------
export const posts = pgTable(
  "posts",
  {
    id: text("id").primaryKey(), // uuid — generated by application
    roughIdea: text("rough_idea"),
    sourceUrl: text("source_url"),       // article URL when drafted from /discover (D-08)
    sourceTitle: text("source_title"),   // article title when drafted from /discover (D-08)
    draftText: text("draft_text"),
    finalText: text("final_text"),
    // 5-dimension tagging (Phase 2)
    hookType: text("hook_type"),
    narrativeStructure: text("narrative_structure"),
    topicId: integer("topic_id").references(() => topicAreas.id),
    scheduledTime: timestamp("scheduled_time"),
    publishedAt: timestamp("published_at"),
    linkedinPostUrl: text("linkedin_post_url"),
    // Engagement metrics (Phase 4 — manually entered or auto-pulled Phase 5)
    reactions: integer("reactions"),
    comments: integer("comments"),
    reposts: integer("reposts"),
    impressions: integer("impressions"),
    engagementRate: real("engagement_rate"), // (reactions + comments + reposts) / impressions
    metricsPulledAt: timestamp("metrics_pulled_at"),
    status: text("status").notNull().default("draft"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (table) => ({
    topicIdx: index("posts_topic_idx").on(table.topicId),
    statusIdx: index("posts_status_idx").on(table.status),
    createdAtIdx: index("posts_created_at_idx").on(table.createdAt),
  })
);

// ---------------------------------------------------------------------------
// PHASE 3 — trending_items (RSS feed items + bookmarks)
// ---------------------------------------------------------------------------
export const trendingItems = pgTable(
  "trending_items",
  {
    id: text("id").primaryKey(), // uuid
    sourceType: text("source_type").notNull(),
    sourceUrl: text("source_url").notNull(),
    title: text("title"),
    summary: text("summary"),
    topicId: integer("topic_id").references(() => topicAreas.id),
    contentHash: text("content_hash").notNull(), // sha256 of url+title for dedup
    fetchedAt: timestamp("fetched_at").notNull().defaultNow(),
    expiresAt: timestamp("expires_at"), // TTL for RSS items
  },
  (table) => ({
    topicIdx: index("trending_topic_idx").on(table.topicId),
    hashIdx: uniqueIndex("trending_hash_idx").on(table.contentHash),
  })
);

// ---------------------------------------------------------------------------
// PHASE 4–5 — performance_bias (singleton, updated weekly by Feedback Engine)
// ---------------------------------------------------------------------------
export const performanceBias = pgTable("performance_bias", {
  id: serial("id").primaryKey(),
  computedAt: timestamp("computed_at").notNull().defaultNow(),
  biasJson: text("bias_json").notNull(), // JSON: ranked tag combos per topic
});

// ---------------------------------------------------------------------------
// PHASE 4–5 — weekly_digests
// ---------------------------------------------------------------------------
export const weeklyDigests = pgTable("weekly_digests", {
  id: text("id").primaryKey(), // uuid
  weekEnding: text("week_ending").notNull(), // ISO date string: "2026-05-05"
  digestJson: text("digest_json").notNull(), // JSON: top performers, underperformers, recommendations
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// TypeScript inferred types — used by query functions throughout the app
// ---------------------------------------------------------------------------
export type VoiceProfile = typeof voiceProfile.$inferSelect;
export type NewVoiceProfile = typeof voiceProfile.$inferInsert;

export type TopicArea = typeof topicAreas.$inferSelect;
export type NewTopicArea = typeof topicAreas.$inferInsert;

export type Post = typeof posts.$inferSelect;
export type NewPost = typeof posts.$inferInsert;

export type TrendingItem = typeof trendingItems.$inferSelect;
export type NewTrendingItem = typeof trendingItems.$inferInsert;

export type PerformanceBias = typeof performanceBias.$inferSelect;
export type WeeklyDigest = typeof weeklyDigests.$inferSelect;

// ---------------------------------------------------------------------------
// LINGUISTIC GUARDRAIL — opening memory (prevents repeated opening structures)
// ---------------------------------------------------------------------------
export const openings = pgTable("openings", {
  id: text("id").primaryKey(),
  openingText: text("opening_text").notNull(),
  fingerprint: text("fingerprint").notNull(),
  contextKey: text("context_key"),
  createdAt: timestamp("created_at").notNull(),
});

export type Opening = typeof openings.$inferSelect;
